// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldBirthday holds the string denoting the birthday field in the database.
	FieldBirthday = "birthday"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"

	// EdgeSex holds the string denoting the sex edge name in mutations.
	EdgeSex = "sex"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// EdgeTitle holds the string denoting the title edge name in mutations.
	EdgeTitle = "title"

	// Table holds the table name of the user in the database.
	Table = "users"
	// SexTable is the table the holds the sex relation/edge.
	SexTable = "users"
	// SexInverseTable is the table name for the Sex entity.
	// It exists in this package in order to avoid circular dependency with the "sex" package.
	SexInverseTable = "sexes"
	// SexColumn is the table column denoting the sex relation/edge.
	SexColumn = "sex_user"
	// RoleTable is the table the holds the role relation/edge.
	RoleTable = "users"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
	// RoleColumn is the table column denoting the role relation/edge.
	RoleColumn = "role_user"
	// TitleTable is the table the holds the title relation/edge.
	TitleTable = "users"
	// TitleInverseTable is the table name for the Title entity.
	// It exists in this package in order to avoid circular dependency with the "title" package.
	TitleInverseTable = "titles"
	// TitleColumn is the table column denoting the title relation/edge.
	TitleColumn = "title_user"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPassword,
	FieldName,
	FieldAge,
	FieldBirthday,
	FieldTel,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the User type.
var ForeignKeys = []string{
	"role_user",
	"sex_user",
	"title_user",
}
