// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Sex is the predicate function for sex builders.
type Sex func(*sql.Selector)

// Title is the predicate function for title builders.
type Title func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
