// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Sujitnapa21/app/ent/role"
	"github.com/Sujitnapa21/app/ent/schema"
	"github.com/Sujitnapa21/app/ent/sex"
	"github.com/Sujitnapa21/app/ent/title"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescRolename is the schema descriptor for rolename field.
	roleDescRolename := roleFields[0].Descriptor()
	// role.RolenameValidator is a validator for the "rolename" field. It is called by the builders before save.
	role.RolenameValidator = roleDescRolename.Validators[0].(func(string) error)
	sexFields := schema.Sex{}.Fields()
	_ = sexFields
	// sexDescSexname is the schema descriptor for sexname field.
	sexDescSexname := sexFields[0].Descriptor()
	// sex.SexnameValidator is a validator for the "sexname" field. It is called by the builders before save.
	sex.SexnameValidator = sexDescSexname.Validators[0].(func(string) error)
	titleFields := schema.Title{}.Fields()
	_ = titleFields
	// titleDescTitlename is the schema descriptor for titlename field.
	titleDescTitlename := titleFields[0].Descriptor()
	// title.TitlenameValidator is a validator for the "titlename" field. It is called by the builders before save.
	title.TitlenameValidator = titleDescTitlename.Validators[0].(func(string) error)
}
