// Code generated by entc, DO NOT EDIT.

package role

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRolename holds the string denoting the rolename field in the database.
	FieldRolename = "rolename"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the role in the database.
	Table = "roles"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "role_user"
)

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldRolename,
}

var (
	// RolenameValidator is a validator for the "rolename" field. It is called by the builders before save.
	RolenameValidator func(string) error
)
