// Code generated by entc, DO NOT EDIT.

package title

const (
	// Label holds the string label denoting the title type in the database.
	Label = "title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitlename holds the string denoting the titlename field in the database.
	FieldTitlename = "titlename"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the title in the database.
	Table = "titles"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "title_user"
)

// Columns holds all SQL columns for title fields.
var Columns = []string{
	FieldID,
	FieldTitlename,
}

var (
	// TitlenameValidator is a validator for the "titlename" field. It is called by the builders before save.
	TitlenameValidator func(string) error
)
