/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRole,
    EntRoleFromJSON,
    EntRoleFromJSONTyped,
    EntRoleToJSON,
    EntSex,
    EntSexFromJSON,
    EntSexFromJSONTyped,
    EntSexToJSON,
    EntTitle,
    EntTitleFromJSON,
    EntTitleFromJSONTyped,
    EntTitleToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * 
     * @type {EntRole}
     * @memberof EntUserEdges
     */
    role?: EntRole;
    /**
     * 
     * @type {EntSex}
     * @memberof EntUserEdges
     */
    sex?: EntSex;
    /**
     * 
     * @type {EntTitle}
     * @memberof EntUserEdges
     */
    title?: EntTitle;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : EntRoleFromJSON(json['role']),
        'sex': !exists(json, 'sex') ? undefined : EntSexFromJSON(json['sex']),
        'title': !exists(json, 'title') ? undefined : EntTitleFromJSON(json['title']),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': EntRoleToJSON(value.role),
        'sex': EntSexToJSON(value.sex),
        'title': EntTitleToJSON(value.title),
    };
}


